<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.2" tiledversion="1.2.2" name="map" tilewidth="32" tileheight="32" tilecount="120" columns="8">
 <image source="../images/basictiles.png" width="256" height="480"/>
 <tile id="0" type="wall"/>
 <tile id="1" type="wall"/>
 <tile id="2" type="wall"/>
 <tile id="3" type="wall"/>
 <tile id="4" type="wall"/>
 <tile id="5" type="wall"/>
 <tile id="6" type="wall"/>
 <tile id="7" type="wall"/>
 <tile id="8" type="wall"/>
 <tile id="9" type="wall"/>
 <tile id="10" type="wall"/>
 <tile id="11" type="wall"/>
 <tile id="12" type="wall"/>
 <tile id="13" type="wall"/>
 <tile id="14" type="wall"/>
 <tile id="15" type="wall"/>
 <tile id="16" type="wall"/>
 <tile id="17" type="wall"/>
 <tile id="18" type="wall"/>
 <tile id="19" type="wall"/>
 <tile id="20" type="pass"/>
 <tile id="21" type="wall"/>
 <tile id="22" type="wall"/>
 <tile id="23" type="wall"/>
 <tile id="24" type="wall"/>
 <tile id="25" type="wall"/>
 <tile id="26" type="wall"/>
 <tile id="27" type="wall"/>
 <tile id="28" type="wall"/>
 <tile id="29" type="wall"/>
 <tile id="30" type="wall"/>
 <tile id="31" type="wall"/>
 <tile id="32" type="wall"/>
 <tile id="33" type="wall"/>
 <tile id="34" type="wall"/>
 <tile id="35" type="wall"/>
 <tile id="36" type="wall"/>
 <tile id="37" type="wall"/>
 <tile id="38" type="wall"/>
 <tile id="39" type="wall"/>
 <tile id="40" type="wall"/>
 <tile id="41" type="wall"/>
 <tile id="42" type="wall"/>
 <tile id="43" type="wall"/>
 <tile id="44" type="wall"/>
 <tile id="45" type="wall"/>
 <tile id="46" type="wall"/>
 <tile id="47" type="wall"/>
 <tile id="48" type="wall"/>
 <tile id="49" type="wall"/>
 <tile id="50" type="wall"/>
 <tile id="51" type="wall"/>
 <tile id="52" type="wall"/>
 <tile id="53" type="wall"/>
 <tile id="54" type="wall"/>
 <tile id="55" type="wall"/>
 <tile id="56" type="wall"/>
 <tile id="57" type="wall"/>
 <tile id="58" type="wall"/>
 <tile id="59" type="wall"/>
 <tile id="60" type="wall"/>
 <tile id="61" type="wall"/>
 <tile id="62" type="wall"/>
 <tile id="63" type="wall"/>
 <tile id="64" type="wall"/>
 <tile id="65" type="wall"/>
 <tile id="66" type="wall"/>
 <tile id="67" type="wall"/>
 <tile id="68" type="wall"/>
 <tile id="69" type="wall"/>
 <tile id="70" type="wall"/>
 <tile id="71" type="wall"/>
 <tile id="72" type="wall"/>
 <tile id="73" type="wall"/>
 <tile id="74" type="wall"/>
 <tile id="75" type="wall"/>
 <tile id="76" type="wall"/>
 <tile id="77" type="wall"/>
 <tile id="78" type="wall"/>
 <tile id="79" type="wall"/>
 <tile id="80" type="wall"/>
 <tile id="81" type="wall"/>
 <tile id="82" type="wall"/>
 <tile id="83" type="wall"/>
 <tile id="84" type="wall"/>
 <tile id="85" type="wall"/>
 <tile id="86" type="wall"/>
 <tile id="87" type="wall"/>
 <tile id="88" type="wall"/>
 <tile id="89" type="wall"/>
 <tile id="90" type="wall"/>
 <tile id="91" type="wall"/>
 <tile id="92" type="wall"/>
 <tile id="93" type="wall"/>
 <tile id="94" type="wall"/>
 <tile id="95" type="wall"/>
 <tile id="96" type="pass"/>
 <tile id="97" type="pass"/>
 <tile id="98" type="pass"/>
 <tile id="99" type="wall"/>
 <tile id="100" type="wall"/>
 <tile id="101" type="wall"/>
 <tile id="102" type="wall"/>
 <tile id="103" type="wall"/>
 <tile id="104" type="pass"/>
 <tile id="105" type="pass"/>
 <tile id="106" type="pass"/>
 <tile id="107" type="wall"/>
 <tile id="108" type="wall"/>
 <tile id="109" type="wall"/>
 <tile id="110" type="wall"/>
 <tile id="111" type="wall"/>
 <tile id="112" type="pass"/>
 <tile id="113" type="pass"/>
 <tile id="114" type="pass"/>
 <tile id="115" type="wall"/>
 <tile id="116" type="wall"/>
 <tile id="117" type="wall"/>
 <tile id="118" type="wall"/>
 <tile id="119" type="wall"/>
</tileset>
